#!/usr/bin/env ruby

existing = `gem list`.split("\n").map { |g| g.gsub(/\((.*?)\)/, '').strip }

gems = [
  'rake', 
  [ 'rspec', '--pre' ],
  'dependencies',
  [ 'activesupport', '--pre' ],
  [ 'activerecord', '--pre' ],
  'mysql',
  'rspec-rails-matchers'
]

gems.each do |gem, flags|
  if existing.include?(gem)
    puts " -> Skipping #{gem}"
  else
    print " -> Installing #{gem} #{flags}... "
    `gem install #{gem} #{flags}`
    puts  "Done!"
  end
end
