development:
  access_key_id: 1QJ6595TXYQJTG9WE3G2
  secret_access_key: P0SiG5MNJwcFloA+7D2V2lHdaXVBPciaA/V5hDSb
 
test:
  access_key_id: abc
  secret_access_key: abc/efg
 
production:
  access_key_id: 1QJ6595TXYQJTG9WE3G2
  secret_access_key: P0SiG5MNJwcFloA+7D2V2lHdaXVBPciaA/V5hDSb
