defaults: &defaults
  :log_level: warn
  :asset_host: ""
  :session:
    :key: "rack.session"
  
  :photos:
    :storage:   :file
    :root:      ':root/public'
    :store_dir: ':root/public/system/uploads'
    :cache_dir: ':root/tmp/uploads'

  :twitter:
    :consumer_key: "45Hgz2NJRhHOH2uSmhfyhg"
    :secret:       "PrMnB5WNnmXwAjw3UtlvnGYESeiXlBkA5hhw0PFi4Lo"
    :return_to:    "/authenticated"

:development:
  <<: *defaults
  :log_level: debug
    

:test:
  <<: *defaults

:production:
  <<: *defaults
  :log_level: debug
  :asset_host: "http://d20r1yy71waydm.cloudfront.net"
  :photos:
    :storage: :s3
    :root:      ':root/public'
    :store_dir: 'uploads'
    :cache_dir: ':root/tmp/uploads'
    :s3_bucket: 'assets.boughtstuff.com'
    :s3_access_key_id: "1K4Y2FT2FFD0WYZJYT02"
    :s3_secret_access_key: "qWCV1IOH/BkkqyrSMuL86/gzbnsC55QxAhy18uD/"

