defaults: &defaults
  :log_level: warn
  :asset_host: ""
  :session:
    :key: "rack.session"
  
  :cache:
    :verbose:     true
    :metastore:   "file:tmp/cache/rack"
    :entitystore: "file:tmp/cache/rack"
    
  :photos:
    :storage:   :file
    :root:      ':root/public'
    :store_dir: ':root/public/system/uploads'
    :cache_dir: ':root/tmp/uploads'

  :twitter:
    :consumer_key: "__key__"
    :secret:       "__secret__"
    :return_to:    "/authenticated"

:development:
  <<: *defaults
  :log_level: debug
    

:test:
  <<: *defaults

:production:
  <<: *defaults
  :log_level: debug
  :asset_host: 
    - "http://assets1.boughtstuff.com"
    - "http://assets2.boughtstuff.com"
    - "http://assets3.boughtstuff.com"
  :photos:
    :storage: :s3
    :root:      ':root/public'
    :store_dir: 'uploads'
    :cache_dir: ':root/tmp/uploads'
    :s3_cnamed: true
    :s3_bucket: 'assets.boughtstuff.com'
    :s3_access_key_id: "__s3__access__"
    :s3_secret_access_key: "__key__"

  :cache:
    :metastore:   "memcached://localhost:11211"
    :entitystore: "memcached://localhost:11211"

