development:
  strategy: oauth
  oauth_consumer_key: key
  oauth_consumer_secret: secret 
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
test: &TEST
  strategy: oauth
  oauth_consumer_key: testkey
  oauth_consumer_secret: testsecret
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"

cucumber:
  <<: *TEST

production:
  strategy: oauth
  oauth_consumer_key: key
  oauth_consumer_secret: secret 
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
